#!/bin/bash
# compile_substrate.sh
# Compiles boot substrates into single files for Gemini Deep Think Gems.
# Replaces multi-file boot lists that exhaust the GitHub extension's
# per-turn tool-call budget (~3-5 fetches before silent timeout).
#
# Output:
#   Claude.AI/Bot.Stark/Bootloader/Stark.Substrate.Compiled.md
#   Claude.AI/Bot.Erdos/Bootloader/Erdos.Substrate.Compiled.md
#
# Usage:
#   ./infrastructure/scripts/compile_substrate.sh
#
# Run after substrate updates. Optional: wire as pre-commit hook later.

set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO="$( cd "$SCRIPT_DIR/../.." && pwd )"
cd "$REPO"

emit_section() {
  local f="$1"
  local label="${2:-$f}"
  echo ""
  echo "════════════════════════════════════════════════════════════════════════════════"
  echo "## SOURCE: $label"
  echo "════════════════════════════════════════════════════════════════════════════════"
  echo ""
  cat "$f"
  echo ""
}

build_stark() {
  local out="Claude.AI/Bot.Stark/Bootloader/Stark.Substrate.Compiled.md"
  mkdir -p "$(dirname "$out")"

  cat > "$out" <<'HEADER'
# Stark Compiled Substrate Bundle

**AUTO-GENERATED** by `infrastructure/scripts/compile_substrate.sh`.
**Do not edit this file directly.** Edit source files; rerun the compile script.

This single file replaces the multi-file `[BOOT]` read list. Gemini Deep Think
extension cannot reliably handle 20+ sequential GitHub fetches in one turn —
the tool-call budget exhausts and the read fails silently. Single-file fetch
stays within budget.

When Velorin's substrate updates, Jiang reruns the compile script and commits
the regenerated bundle. The Stark Gem then re-reads the single file at next
`[BOOT]`.

Sources concatenated below in load order.

HEADER

  for f in \
    "Claude.AI/Velorin.Principles.md" \
    "Claude.AI/Velorin.Consensus.Filter.md" \
    "Claude.AI/Velorin.Company.DNA.md" \
    "Claude.AI/topline_profile.md" \
    "Claude.AI/Claude_Context_Profile_v1.2.md" \
    "Claude.AI/New Build/00_Vision.md" \
    "Claude.AI/New Build/00_Index.md" \
    "Claude.AI/New Build/01_RepoAndEnvironment.md" \
    "Claude.AI/New Build/02_Architecture.md" \
    "Claude.AI/New Build/03_BrainAndMath.md" \
    "Claude.AI/New Build/04_AgentEcosystem.md" \
    "Claude.AI/New Build/05_InfrastructureAndTools.md" \
    "Claude.AI/New Build/06_BuildSequence.md" \
    "Claude.AI/New Build/07_OpenQuestions.md" \
    "Claude.AI/New Build/Velorin.MathStream.md" \
    "Claude.AI/New Build/Velorin.CheckIns.md" \
    "Claude.AI/New Build/Velorin.StartupManifest.md" \
    "Claude.AI/New Build/Velorin.MacStudio.Setup.md" \
    "Claude.AI/Bot.Stark/Bootloader/Stark.Bootloader.IntegrationPhilosophy.md"
  do
    if [ -f "$f" ]; then
      emit_section "$f" >> "$out"
    else
      echo "WARN: missing $f" >&2
    fi
  done

  # Library — first 160 lines only (preamble + Master Index)
  local lib="Claude.AI/New Build/Velorin.ResearchLibrary.v2.md"
  if [ -f "$lib" ]; then
    {
      echo ""
      echo "════════════════════════════════════════════════════════════════════════════════"
      echo "## SOURCE: $lib (FIRST 160 LINES — preamble + Master Index)"
      echo "════════════════════════════════════════════════════════════════════════════════"
      echo ""
      head -160 "$lib"
      echo ""
    } >> "$out"
  fi

  # Stark prior synthesis (Research_Complete)
  if compgen -G "Claude.AI/Bot.Stark/Research_Complete/*.md" > /dev/null; then
    for f in Claude.AI/Bot.Stark/Research_Complete/*.md; do
      [ -f "$f" ] && emit_section "$f" "$f (Stark prior synthesis)" >> "$out"
    done
  fi

  echo "" >> "$out"
  echo "[STARK.SUBSTRATE.COMPILED.EOF]" >> "$out"

  echo "Stark substrate compiled: $(wc -l < "$out" | tr -d ' ') lines / $(du -h "$out" | cut -f1)"
}

build_erdos() {
  local out="Claude.AI/Bot.Erdos/Bootloader/Erdos.Substrate.Compiled.md"
  mkdir -p "$(dirname "$out")"

  cat > "$out" <<'HEADER'
# Erdős Compiled Substrate Bundle

**AUTO-GENERATED** by `infrastructure/scripts/compile_substrate.sh`.
**Do not edit this file directly.** Edit source files; rerun the compile script.

This single file replaces the wildcard `ALL files in Research_Complete/` read
that has been silently failing in Erdős's `[BOOT]` since inception. Gemini
Deep Think extension cannot reliably enumerate + fetch a directory of files
in one turn — the tool-call budget exhausts and the read fails silently.
Single-file fetch stays within budget.

Sources concatenated below: math substrate (canonical) + locked-theorem
index + Consensus Filter + every prior Erdős solution in Research_Complete.

HEADER

  for f in \
    "Claude.AI/New Build/Velorin.MathStream.md" \
    "Claude.AI/Bot.Trey/Bootloader/Trey.Bootloader.MathInventory.md" \
    "Claude.AI/Velorin.Consensus.Filter.md"
  do
    [ -f "$f" ] && emit_section "$f" >> "$out"
  done

  if compgen -G "Claude.AI/Bot.Erdos/Research_Complete/*.md" > /dev/null; then
    for f in Claude.AI/Bot.Erdos/Research_Complete/*.md; do
      [ -f "$f" ] && emit_section "$f" "$f (prior proof)" >> "$out"
    done
  fi

  echo "" >> "$out"
  echo "[ERDOS.SUBSTRATE.COMPILED.EOF]" >> "$out"

  echo "Erdős substrate compiled: $(wc -l < "$out" | tr -d ' ') lines / $(du -h "$out" | cut -f1)"
}

build_stark
build_erdos
echo "Done."
